# Makefile for VMTD and DOS-based programs. CREATEVM needs to be compiled
# with Microsoft Visual C/C++ 1.5

#DEBUG_GOVM     =   TRUE                ; comment out for final build


OUTPUT  =   aux
WINAPPS =   c:\mwin
WINLIB  =   c:\MSVC\lib
WININC  =   c:\MSVC\include
!IFNDEF WINDIR
WINDIR  =   c:\mwin
!ENDIF


#
# for GOVM.EXE build; DOS app
#
!IFDEF DEBUG_GOVM
IDAS =   masm /Zi
IDCC =   cl -c -Zi /I$(WININC)
IDLN =   link /Co
IDZZ =   GOVM: ***** DEBUG ***** DEBUG ***** DEBUG ***** DEBUG *****
!ELSE
IDAS =   masm
IDCC =   cl -c /I$(WININC)
IDLN =   link
IDZZ =   GOVM: **** RELEASE *** RELEASE *** RELEASE *** RELEASE ****
!ENDIF

IDSRCS   =   govm.c
IDOBJS   =   govm.obj


#
# now the rules
#
all         :   govm.exe
                @echo ================= BUILD COMPLETE ===================
                @echo $(IDZZ)
                @echo ================= BUILD COMPLETE ===================


# GOVM.EXE
govm.exe :      $(IDOBJS)
                $(IDLN) @govm.lnk
                @echo $(IDZZ)

govm.obj :      govm.c
                $(IDCC) $*.c
                
                
# MISC JUNK
clean   :
            del *.386
            del *.lib
            del *.dll
            del *.exe
            del *.res
            del *.obj
            del *.sym
            del *.map
            del *.lst
            del *.zip

zip     :   clean
            pkzip -a govm.zip *.*

ship    :   all
            del *.lib
            del *.res
            del *.obj
            del *.sym
            del *.map
            del *.lst
            del *.zip
            touch /n *.*
            pkzip -a govm.zip *.*
